import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/**
 * Utility to add tilt effect to an element
 */
export function addTiltEffect(element: HTMLElement, intensity: number = 20) {
  const handleMouseMove = (e: MouseEvent) => {
    if (document.body.classList.contains('reduced-motion')) return;
    
    const rect = element.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;
    
    const centerX = rect.width / 2;
    const centerY = rect.height / 2;
    
    const tiltX = (y - centerY) / intensity;
    const tiltY = (centerX - x) / intensity;
    
    element.style.transform = `perspective(1000px) rotateX(${tiltX}deg) rotateY(${tiltY}deg) scale3d(1.05, 1.05, 1.05)`;
  };
  
  const handleMouseLeave = () => {
    element.style.transform = 'perspective(1000px) rotateX(0) rotateY(0) scale3d(1, 1, 1)';
  };
  
  element.addEventListener('mousemove', handleMouseMove);
  element.addEventListener('mouseleave', handleMouseLeave);
  
  // Return cleanup function
  return () => {
    element.removeEventListener('mousemove', handleMouseMove);
    element.removeEventListener('mouseleave', handleMouseLeave);
  };
}

/**
 * Utility to generate PDF resume
 */
export function generateResume() {
  import('jspdf').then(({ default: jsPDF }) => {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });
    
    // Add header
    doc.setFontSize(24);
    doc.setTextColor(0, 255, 194); // Teal color
    doc.text('Diwanshu Yadav', 20, 20);
    
    // Add subtitle/roles
    doc.setFontSize(12);
    doc.setTextColor(80, 80, 80);
    doc.text('AI Architect • Full-Stack Alchemist • Creative Technologist', 20, 28);
    
    // Contact info
    doc.setFontSize(10);
    doc.setTextColor(40, 40, 40);
    doc.text('diwanshu.yadav@example.com • linkedin.com/in/diwanshuyadav', 20, 35);
    
    // Section: About
    doc.setFontSize(14);
    doc.setTextColor(255, 0, 170); // Magenta
    doc.text('About', 20, 45);
    
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text('Creating intelligent, immersive experiences that push technological boundaries', 20, 52);
    doc.text('while remaining accessible and human-centered.', 20, 57);
    
    // Section: Skills
    doc.setFontSize(14);
    doc.setTextColor(255, 0, 170); 
    doc.text('Skills', 20, 67);
    
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    const skills = [
      'Python (Machine Learning, Data Science, Backend)',
      'C++ (Performance-critical applications, Game Dev)',
      'Web Development (React, Next.js, Three.js, GSAP)',
      'Machine Learning (Neural Networks, NLP, Computer Vision)',
      'Databases (SQL, MongoDB, Firebase, Redis)',
      'Version Control (Git, GitHub, CI/CD Pipelines)'
    ];
    
    let yPosition = 74;
    skills.forEach(skill => {
      doc.text('• ' + skill, 20, yPosition);
      yPosition += 5;
    });
    
    // Section: Projects
    doc.setFontSize(14);
    doc.setTextColor(255, 0, 170);
    doc.text('Projects', 20, yPosition + 5);
    
    // Project 1
    yPosition += 12;
    doc.setFontSize(12);
    doc.setTextColor(0, 200, 255); // Blue
    doc.text('Neural Vision System', 20, yPosition);
    
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text('Computer vision platform for real-time object detection and tracking', 20, yPosition + 5);
    doc.text('Technologies: Python, TensorFlow, OpenCV, CUDA, Docker', 20, yPosition + 10);
    
    // Project 2
    yPosition += 20;
    doc.setFontSize(12);
    doc.setTextColor(0, 200, 255);
    doc.text('DataSphere Explorer', 20, yPosition);
    
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text('3D interactive data visualization platform with real-time analysis', 20, yPosition + 5);
    doc.text('Technologies: JavaScript, Three.js, D3.js, WebGL, React', 20, yPosition + 10);
    
    // Project 3
    yPosition += 20;
    doc.setFontSize(12);
    doc.setTextColor(0, 200, 255);
    doc.text('Autonomous Agent Framework', 20, yPosition);
    
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text('Multi-agent system for automated decision making and task orchestration', 20, yPosition + 5);
    doc.text('Technologies: C++, Rust, Reinforcement Learning, Distributed Systems', 20, yPosition + 10);
    
    // Footer
    const pageCount = doc.getNumberOfPages();
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.text('Generated by DiwanshuOS - ' + new Date().toLocaleDateString(), 20, 285);
    }
    
    // Save PDF
    doc.save('Diwanshu_Yadav_Resume.pdf');
  }).catch(err => {
    console.error('Error generating PDF:', err);
    alert('Error generating PDF resume. Please try again later.');
  });
}
